<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Infra.AI\Infra.AI.csproj" />
    <ProjectReference Include="..\Infra.MessageBus\Infra.MessageBus.csproj" />
  </ItemGroup>

</Project>
